### ISSUE TITLE
cannot load model

### ISSUE THREAD

**Issue by mehraban72** [UniversalDependencies/UD_Persian#4]
Hi 
when I run nlp = stanford nlp.Pipeline()  I give error
Use device: cpu
---
Loading: tokenize
With settings: 
{'model_path': 'C:\\Users\\user\\stanfordnlp_resources\\en_ewt_models\\en_ewt_tokenizer.pt', 'lang': 'en', 'shorthand': 'en_ewt', 'mode': 'predict'}
Cannot load model from C:\Users\user\stanfordnlp_resources\en_ewt_models\en_ewt_tokenizer.pt
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

**Comment by dan-zeman** [comment]
This issue seems to belong to a different repository. It is not about the UD data, and specifically not about the treebank UD_Persian-Seraji.
